config/routes.rb
Rails.application.routes.draw do

  resources :issues
  resources :github_tokens

  resources :test_suites do
    resources :features do
      member do
        post 'approve'
      end
    end
  end

  resource :user
  get 'users', to: 'users#index'
  resources :user_sessions, only: [:create]
  get 'logout', to: 'user_sessions#destroy', as: 'logout'

  root to: 'user_sessions#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.require_password_confirmation = false
  end
  has_many :testers
  has_many :test_suites, through: :testers
  has_many :approvals, through: :testers
  has_many :features, through: :approvals

  def can_approve?(feature)
    test_suites.include?(feature.test_suite)
  end

  def last_approved(feature)
    feature_approvals = approvals.where(feature_id: feature.id)
    feature_approvals.any? && feature_approvals.last.created_at
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  before_action :require_admin, except: [:show, :edit, :update]
  before_action :set_user, except: [:new, :create, :destroy]

  # GET /user
  def show
    @test_suite = TestSuite.active.last
  end

  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @new_user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @new_user = User.new(user_params)
    if @new_user.save_without_session_maintenance
      redirect_to user_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    password_validation = params[:user][:password_validation]
    valid_password      = @user.valid_password?(password_validation)
    if valid_password && @user.update(user_params)
      redirect_to user_path, notice: 'User was successfully updated.'
    else
      @user.errors.add(:password)
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/views/users/edit.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Edit User</h1>

      <%= simple_form_for(@user) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :email %>
          <%= f.input :password_validation %>
          <%= f.input :password, label: 'New password' %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>

      <%= link_to 'Back', user_path %>
    </div>
  </section>
<% end %>

app/views/users/index.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Listing User</h1>
      <p>
        <%= link_to 'New User', new_user_path %>
      </p>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Email</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
<% end %>

app/views/users/new.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>New User</h1>

      <%= simple_form_for(@new_user, url: user_path) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :email %>
          <%= f.input :password %>
          <%= f.input :admin %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </section>
<% end %>

app/views/users/show.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <ul>
        <% if @test_suite %>
          <li><%= link_to "Latest test suite", test_suite_path(@test_suite), class: 'btn btn-default' %></li>
        <% end %>
        <li><%= link_to "Test suites", test_suites_path, class: 'btn btn-default' %></li>
        <% if @user.admin %>
          <li><%= link_to "Github Tokens", github_tokens_path, class: 'btn btn-default' %></li>
          <li><%= link_to "Users", users_path, class: 'btn btn-default' %></li>
        <% end %>

      </ul>
      <%= link_to 'Edit', edit_user_path, class: 'btn btn-primary' %>
    </div>
  </section>
<% end %>