config/routes.rb
Rails.application.routes.draw do

  resources :issues
  resources :github_tokens

  resources :test_suites do
    resources :features do
      member do
        post 'approve'
      end
    end
  end

  resource :user
  get 'users', to: 'users#index'
  resources :user_sessions, only: [:create]
  get 'logout', to: 'user_sessions#destroy', as: 'logout'

  root to: 'user_sessions#new'
end

app/models/github_token.rb
class GithubToken < ActiveRecord::Base
  validates_length_of :access_token, :minimum => 40, :maximum => 40

  def client
    Octokit::Client.new(access_token: access_token)
  end

  def repos
    return client.repos unless organization
    client.org_repos(organization)
  rescue
    []
  end
end

app/controllers/github_tokens_controller.rb
class GithubTokensController < ApplicationController
  before_action :require_user
  before_action :require_admin
  before_action :set_github_token, only: [:show, :edit, :update, :destroy]

  # GET /github_tokens
  def index
    @github_tokens = GithubToken.all
  end

  # GET /github_tokens/1
  def show
    @repos = @github_token.repos.map { |r| r[:full_name] }
  end

  # GET /github_tokens/new
  def new
    @github_token = GithubToken.new
  end

  # GET /github_tokens/1/edit
  def edit
  end

  # POST /github_tokens
  def create
    @github_token = GithubToken.new(github_token_params)
    if @github_token.save
      redirect_to @github_token, notice: 'Github token was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /github_tokens/1
  def update
    if @github_token.update(github_token_params)
      redirect_to @github_token, notice: 'Github token was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /github_tokens/1
  def destroy
    @github_token.destroy
    redirect_to github_tokens_url, notice: 'Github token was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_github_token
      @github_token = GithubToken.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def github_token_params
      params.require(:github_token).permit(:access_token, :title, :organization)
    end
end

app/views/github_tokens/_form.html.erb
<%= simple_form_for(@github_token) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :organization %>
    <%= f.input :access_token %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/github_tokens/edit.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Edit Github_token</h1>

      <%= render 'form' %>

      <%= link_to 'Back', github_tokens_path %>
    </div>
  </section>
<% end %>

app/views/github_tokens/index.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Listing Github_tokens</h1>
      <p>
        <%= link_to 'New GithubToken', new_github_token_path %>
      </p>

      <%= generate_table(
        striped: true,
        data_table: true,
        header: ['Title', '', '', ''],
        content: @github_tokens.map do |github_token|
          [
            github_token.title,
            link_to('Show', github_token_path(github_token)),
            link_to('Edit', edit_github_token_path(github_token)),
            link_to('Destroy', github_token, method: :delete, data: { confirm: 'Are you sure?' })
          ]
        end) %>
    </div>
  </section>
<% end %>

app/views/github_tokens/new.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>New Github_token</h1>

      <%= render 'form' %>

      <%= link_to 'Back', github_tokens_path %>
    </div>
  </section>
<% end %>

app/views/github_tokens/show.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h2>
        <%= @github_token.title %>
      </h2>
      <p>Below all are all repos granted access by this token:</p>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Repositories</th>
          </tr>
        </thead>

        <tbody>
          <% @repos.each do |repo_name| %>
            <tr>
              <td><%= repo_name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  
      <%= link_to 'Back', github_tokens_path, class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_github_token_path(@github_token), class: 'btn btn-primary' %>
    </div>
  </section>
<% end %>