config/routes.rb
Rails.application.routes.draw do

  resources :issues
  resources :github_tokens

  resources :test_suites do
    resources :features do
      member do
        post 'approve'
      end
    end
  end

  resource :user
  get 'users', to: 'users#index'
  resources :user_sessions, only: [:create]
  get 'logout', to: 'user_sessions#destroy', as: 'logout'

  root to: 'user_sessions#new'
end

app/models/test_suite.rb
class TestSuite < ActiveRecord::Base
  validates_presence_of :name, :status
  has_many :testers, dependent: :destroy
  has_many :users, through: :testers
  has_many :features, dependent: :destroy
  has_many :issues, dependent: :destroy
  belongs_to :github_token
  enum status: [:in_build, :active, :archieved]
end

app/controllers/test_suites_controller.rb
class TestSuitesController < ApplicationController
  before_action :require_user
  before_action :set_test_suite, only: [:show, :edit, :update, :destroy]
  before_action :set_form_dependencies, only: [:edit, :new]

  # GET /test_suites
  def index
    @test_suites = TestSuite.all
    @test_suites = @test_suites.active unless current_user.admin
  end

  # GET /test_suites/1
  def show
    @features = @test_suite.features
    @testers  = @test_suite.testers.includes(:user)
    @issues   = @test_suite.issues
  end

  # GET /test_suites/new
  def new
    @test_suite = TestSuite.new
  end

  # GET /test_suites/1/edit
  def edit
  end

  # POST /test_suites
  def create
    @test_suite = TestSuite.new(test_suite_params)

    if @test_suite.save
      redirect_to @test_suite, notice: 'Test suite was successfully created.'
    else
      set_form_dependencies
      render :new
    end
  end

  # PATCH/PUT /test_suites/1]
  def update
    if @test_suite.update(test_suite_params)
      redirect_to @test_suite, notice: 'Test suite was successfully updated.'
    else
      set_form_dependencies
      render :edit
    end
  end

  # DELETE /test_suites/1
  def destroy
    @test_suite.destroy
    redirect_to test_suites_url, notice: 'Test suite was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_suite
      @test_suite = TestSuite.find(params[:id])
    end

    def set_form_dependencies
      @users = User.all
      @github_tokens = GithubToken.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_suite_params
      params.require(:test_suite).permit(:name, :description, :repo, :github_token_id, :status, user_ids: [])
    end
end

app/views/test_suites/_form.html.erb
<%= simple_form_for(@test_suite) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.association :users, collection: @users.map { |user| [user.email, user.id] }, input_html: { multiple: true, class: 'js-chosen' } %>
    <%= f.association :github_token, collection: @github_tokens.map { |token| [token.title, token.id] } %>
    <%= f.input :repo %>
    <% if current_user.admin %>
      <%= f.input :status, collection: TestSuite.statuses.keys %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/test_suites/edit.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Edit Test_suite</h1>

      <%= render 'form' %>

      <%= link_to 'Back', test_suites_path %>
    </div>
  </section>
<% end %>

app/views/test_suites/index.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>Listing TestSuites - <%= link_to 'New TestSuite', new_test_suite_path, class: 'btn btn-primary btn-xs' %></h1>
      <%= generate_table(
        striped: true,
        data_table: true,
        header: ['Status', 'Name', 'Description', 'Repo','', '', ''],
        content: @test_suites.map do |test_suite|
          [
            test_suite.status,
            test_suite.name,
            test_suite.description,
            test_suite.repo,
            link_to('Show', test_suite_path(test_suite)),
            link_to('Edit', edit_test_suite_path(test_suite)),
            link_to('Destroy', test_suite, method: :delete, data: { confirm: 'Are you sure?' })
          ]
        end) %>
    </div>
  </section>
<% end %>

app/views/test_suites/new.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
      <h1>New Test_suite</h1>

      <%= render 'form' %>

      <%= link_to 'Back', test_suites_path %>
    </div>
  </section>
<% end %>

app/views/test_suites/show.html.erb
<% content_for :content do %>
  <section>
    <div class="container">
    <h2><%= @test_suite.name %></h2>
      <p>
        <%= @test_suite.description %>
      </p>
      <% if @test_suite.repo %>
        <p>
          <%= "Connected to: #{@test_suite.repo}" %>
        </p>
      <% end %>
    </div>
  </section>
  <section>
    <div class="container">
      <h3>Listing Features - <%= link_to 'New Feature', new_test_suite_feature_path(@test_suite), class: 'btn btn-primary btn-xs' %></h3>
      <%= generate_table(
        striped: true,
        data_table: true,
        header: ['Name'] + @testers.map { |tester| tester.user.email },
        content: @features.map do |feature|
          [link_to(feature.name, test_suite_feature_path(@test_suite, feature))] +
          @testers.map { |tester| tester.user.last_approved(feature) || '-' }
        end) %>
    </div>
  </section>
  <section>
    <div class="container">
      <h3>Issues</h3>
      <%= render 'issues/issue_list', issues: @issues %>
    </div>
  </section>
  <section>
    <div class="container">
      <%= link_to 'Create issue', new_issue_path(test_suite_id: @test_suite.id), class: 'btn btn-danger' %>
      <%= link_to 'Back', test_suites_path, class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_test_suite_path(@test_suite), class: 'btn btn-primary' %>
    </div>
  </section>
<% end %>