config/routes.rb
Rails.application.routes.draw do

  resources :issues
  resources :github_tokens

  resources :test_suites do
    resources :features do
      member do
        post 'approve'
      end
    end
  end

  resource :user
  get 'users', to: 'users#index'
  resources :user_sessions, only: [:create]
  get 'logout', to: 'user_sessions#destroy', as: 'logout'

  root to: 'user_sessions#new'
end

app/views/layouts/_footer.html.erb
<section class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        &copy; <%= Time.now.year %> Copyright Albin. All rights reserved.
      </div>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <% if current_user %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".first-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <% end %>
      <%= link_to user_path, class: 'navbar-brand' do %>
        <%= image_tag 'https://placehold.it/200x100&text=logo', class: 'logo' %>
      <% end %>
    </div>
    <% if current_user %>
      <div class="navbar-collapse navbar-right first-navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if current_user.admin %>
            <li><%= link_to "Github Tokens", github_tokens_path %></li>
          <% end %>
          <li><%= link_to "Test suites", test_suites_path %></li>
          <li><%= link_to "Issues", issues_path %></li>
          <li><%= link_to "Log out", logout_path %></li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Rails.application.class.parent_name %></title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page-wrap">
  <%= render "layouts/navbar" %>
  <%= yield(:content) %>
</div>
<%= render "layouts/footer" %>

</body>
</html>